_hcwp_texts = {
	"yesterday at": "昨天的 {{time}}",
	"before yesterday": "两天前的 {{time}}",
	"days": [
		"天",
		"天",
		"天"
	],
	"hours": [
		"小时",
		"小时",
		"小时"
	],
	"minutes": [
		"分钟",
		"分钟",
		"分钟"
	],
	"seconds": [
		"秒钟",
		"秒钟",
		"秒钟"
	],
	"time_plural": "{{time}} {{interval}} 前",
	"About": "关于此工具",
	"Comments": "评论",
	"New": "最新",
	"Popular": "热门",
	"Quotes": "引用",
	"Code": "建立您的工具",
	"Tree View": "树状图",
	"Login": "登录",
	"Logout": "退出",
	"Enter Email": "邮箱",
	"show more": "更多",
	"First": "最前",
	"Last": "最后",
	"Attach files": "添加",
	"now": "现在",
	"Your message is defined as flood": "评论频率过快，请稍后再试",
	"access denied": "没有足够的权限以进行此操作、或是您的帐号可能已被封禁",
	"last comments": "最新评论",
	"popular pages": "热门",
	"Enter link to the video (YouTube, Vimeo)": "请输入视频链接（仅支持YouTube、Vimeo）",
	"Enter link to the Google Presentation": "请输入Google Presentation链接",
	"Complain send": "已举报",
	"Add complaint": "举报",
	"ban user": "该用户已被封禁",
	"Add accent": "添加优秀评论",
	"hide": "隐藏",
	"Need Auth": "请登录",
	"Email subscribe": "订阅",
	"Show all replies": "显示所有回复",
	"Hide replies": "隐藏回复",
	"Show comment": "展开评论",
	"Hide comment": "隐藏评论",
	"Compact": "紧凑",
	"authorization": "登录",
	"anonymously": "匿名",
	"Your nick": "昵称",
	"Send": "确定",
	"Attach": "添加",
	"Warning": "警告",
	"Mark as spam": "屏蔽",
	"Moderator": "管理员",
	"Reply": "回复",
	"Delete": "删除",
	"Edit": "编辑",
	"Context": "只看此对话",
	"accent comment": "优秀评论",
	"Accent": "优秀评论",
	"Link": "复制链接",
	"Message Pre-Moderate": "评论待审核",
	"Complaint": "举报",
	"Spam": "已屏蔽评论",
	"Ban": "用户被封禁",
	"Moderate": "管理员",
	"Message deleted": "评论已删除",
	"Comment marked as spam": "评论已被屏蔽",
	"more": "更多",
	"replies": "回复",
	"Link was copied": "链接已复制",
	"image": "图片",
	"video": "视频",
	"presentation": "介绍",
	"Enter text": "输入内容",
	"crossposting to": "发表到",
	"Category": "类别",
	"Add comment": "发送",
	"Cancel": "取消",
	"Save": "保存",
	"Close discussion": "关闭讨论",
	"Enter your message before sending": "请输入内容",
	"long comment": "长评论",
	"comment send": "评论已发送",
	"New Comments": "新的评论",
	"close": "关闭",
	"Like": " ",
	"Share to Google+": "分享到Google+",
	"Share to Facebook": "分享到Facebook",
	"Share to Twitter": "分享到Twitter",
	"Share to VK": "分享到VK",
	"no accents": "没有优秀评论",
	"Comments and accents author": "优秀评论者",
	"old browsers": "请使用新版浏览器",
	"Views quotes": "查看引用"
};